---
kind: pipeline
type: docker
name: default

steps:
- name: go-build
  image: golang:1.19.2
  pull: if-not-exists  
  commands:
  - go mod init main
  - go mod tidy
  - go build
  
- name: go-publish
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo: ljw4010/ljw4010
    tags: latest
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
      
- name: BD-scan
  image: blackducksoftware/blackduck-scan:2022.10.1
  settings:
    network: host
    detect.docker.passthrough.shared.dir.path.local: /drone/src
    detect.docker.passthrough.shared.dir.path.imageinspector: /drone/src
    detect.tools: DOCKER
    detect.project.name: go-test
    detect.project.version.name: test-01
    detect.code.location.name: gozbx-sender
    detect.bom.aggregate.name: agg-go
    blackduck.offline.mode: true
    detect.docker.image: ljw4010/ljw4010
    volumes:
      - name: cache
        path: /drone/src
trigger:
  branch:
  - test1
  
volumes:
- name: cache
  temp: {}
