---
kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang:1.19.2
  commands:
  - go mod init main
  - go mod tidy
  - go build
steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: ljw4010/ljw4010
    auto_tag: true
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - test1
