---
kind: pipeline
type: exec
name: BD

steps:
- name: BD-scan
  commands:
  - curl -O https://blackducksoftware.github.io/blackduck-docker-inspector/blackduck-docker-inspector.sh
  - bash blackduck-docker-inspector.sh --upload.bdio=false --docker.image=ljw4010/ljw4010
  
trigger:
  branch:
  - test1
